### ISSUE TITLE
No module named proplot

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Jhsmit/PyHDX#244]
I run

```bash
pip install pyhdx==0.4.0b6
```

```bash
$ pyhdx serve
Traceback (most recent call last):
  File "C:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\repos\private\awesome-panel\.venv\Scripts\pyhdx.exe\__main__.py", line 4, in <module>
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\cli.py", line 3, in <module>
    from pyhdx.web import serve
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\serve.py", line 11, in <module>
    from pyhdx.web.apps import main_app  # , diff_app, single_app, folding_app, full_deuteration_app
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\apps.py", line 8, in <module>
    from pyhdx.web.constructor import AppConstructor
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\constructor.py", line 7, in <module>
    from pyhdx.web.controllers import *
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\controllers.py", line 15, in <module>
    from proplot import to_hex
ModuleNotFoundError: No module named 'proplot'
```

**Comment by MarcSkovMadsen** [comment]
If I run

```bash
pip install pyhdx[web]==0.4.0b6
```

I get proplot installed but then I get

```bash
$ pyhdx serve
c:\repos\private\awesome-panel\.venv\lib\site-packages\proplot\__init__.py:71: ProplotWarning: Rebuilding font cache. This usually happens after installing or updating proplot.
  register_fonts(default=True)
Traceback (most recent call last):
  File "C:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\repos\private\awesome-panel\.venv\Scripts\pyhdx.exe\__main__.py", line 4, in <module>
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\cli.py", line 3, in <module>
    from pyhdx.web import serve
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\serve.py", line 11, in <module>
    from pyhdx.web.apps import main_app  # , diff_app, single_app, folding_app, full_deuteration_app
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\apps.py", line 8, in <module>
    from pyhdx.web.constructor import AppConstructor
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\constructor.py", line 7, in <module>
    from pyhdx.web.controllers import *
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\controllers.py", line 23, in <module>
    from pyhdx.plot import dG_scatter_figure, ddG_scatter_figure, linear_bars_figure, \
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\plot.py", line 691, in <module>
    'rfu': set_bad(pplt.Colormap(cc.cm.gouldian), '#8c8c8c'),
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\colorcet\__init__.py", line 52, in __getattr__
    return self[name] if not name.startswith('_') else super(AttrODict, self).__getattr__(name)
KeyError: 'gouldian'
```

**Comment by MarcSkovMadsen** [comment]
Ok. I was in a virtualenv with colorcet 2.0.2

```bash
pip install colorcet -U
```

solved that problem.

**Comment by MarcSkovMadsen** [comment]
Next problem

```bash
$ pyhdx serve
Started new Dask LocalCluster at 127.0.0.1:52123
Welcome to the PyHDX server!
Launching server at http://localhost:65239
The field 'source' is not specified for view 'logging_info'
The field 'source' is not specified for view 'logging_debug'
The field 'source' is not specified for view 'peptide_overlay'
The field 'source' is not specified for view 'gibbs_overlay'
The field 'source' is not specified for view 'ddG_overlay'
The field 'source' is not specified for view 'protein'
tornado.application - ERROR - Uncaught exception GET /main (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:65239', method='GET', uri='/main', version='HTTP/1.1', remote_ip='127.0.0.1')    
Traceback (most recent call last):
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\server.py", line 214, in get
    session = await self.get_session()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\views\session_handler.py", line 144, in get_session     
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\contexts.py", line 243, in create_session_if_needed     
    self._application.initialize_document(doc)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\server.py", line 173, in initialize_document
    super().initialize_document(doc)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\application\application.py", line 194, in initialize_document  
    h.modify_document(doc)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\application\handlers\function.py", line 143, in modify_document
    self._func(doc)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\server.py", line 78, in _eval_panel
    panel = panel()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\serve.py", line 15, in <lambda>
    'main': lambda: main_app()[1],
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\log.py", line 63, in wrapper
    return function(*args, **kwargs)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\apps.py", line 19, in main_app
    ctrl = ctr.parse(yaml_dict)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\constructor.py", line 58, in parse
    **kwargs, **main_ctrl
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\main_controllers.py", line 97, in __init__
    super(PyHDXController, self).__init__(*args, **kwargs)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\main_controllers.py", line 48, in __init__
    self.control_panels = {ctrl.name: ctrl(self) for ctrl in control_panels}  #todo as param?
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\main_controllers.py", line 48, in <dictcomp>
    self.control_panels = {ctrl.name: ctrl(self) for ctrl in control_panels}  #todo as param?
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\controllers.py", line 860, in __init__
    self.quantity = quantity_options[0]
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 316, in _f
    instance_param.__set__(obj, val)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 318, in _f
    return f(self, obj, val)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 984, in __set__
    obj.param._call_watcher(watcher, event)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1645, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 520, in caller
    return function()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pyhdx\web\controllers.py", line 981, in _quantity_updated
    self.no_coverage = to_hex(cmap.get_bad(), keep_alpha=False)
AttributeError: 'ContinuousColormap' object has no attribute 'get_bad'
```

**Comment by MarcSkovMadsen** [comment]
Ok. Started over in a fresh virtual environment

```bash
python -m venv .venv
pip install pyhdx[web]==0.4.0b6
pyhdx serve
```

And it works.

![image](https://user-images.githubusercontent.com/42288570/146245734-7395ccd3-123b-4ff7-8fb4-f9f5237f59e7.png)

**Comment by Jhsmit** [comment]
Thanks for the issue though. Especially proplot is very finicky with versions. And there are a lot of dependencies so for me its always fingers crossed when I pip install in a fresh env
